spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: book-service-route
          uri: http://localhost:8080
          predicates:
            - Path=/api/books/**

server:
  port: 8222
