spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: book-service-route
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/api/books/**

server:
  port: 8222


eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
