create table author
(
    id                  bigint primary key generated by default as identity,
    name                varchar(255)
);

create table book
(
    id                  bigint primary key generated by default as identity,
    publication_year    integer,
    title               varchar(255),
    author_id           bigint
);