services:
  book-service:
    build:
      context: /book-service/.
    container_name: app
    image: my-app:latest
    expose:
      - "8081"
    depends_on:
      - postgres
      - eureka-service
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin

  notification-service:
    build:
      context: /notification/.
    image: my-notification:latest
    expose:
      - "8082"
    depends_on:
      - eureka-service
    environment:
      - SERVER_PORT=8082


  eureka-service:
    build:
      context: /eureka-server/.
    container_name: eureka-service
    image: eureka-server:latest
    ports:
      - "8761:8761"


  gateway:
    build: /gateway/.
    image: gateway:latest
    depends_on:
      - eureka-service
      - book-service
      - notification-service
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080

  postgres:
    container_name: postgresql
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    ports:
      - "5000:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

