services:
  postgres:
    container_name: postgresql
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5000:5432
    restart: unless-stopped
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  postgres: