#Task 4
services:
  app:
    build:
        context: .
    container_name: app
    image: my-app:latest
    ports:
      - 8080:8080

  postgres:
    container_name: postgresql
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    ports:
      - 5000:5432