#Task 4
#services:
#  app:
#    build:
#        context: .
#    container_name: app
#    image: my-app:latest
#    ports:
#      - 8080:8080
#
#  postgres:
#    container_name: postgresql
#    image: postgres:14-alpine
#    environment:
#      POSTGRES_USER: admin
#      POSTGRES_PASSWORD: admin
#      POSTGRES_DB: db
#    ports:
#      - 5000:5432
#



#Task 5
services:
  app:
    build:
      context: .
    container_name: app
    image: my-app:latest
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"

  postgres:
    container_name: postgresql
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    ports:
      - 5000:5432